[package]
name = "tokio-cron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
cron = "0.12.0"
tokio = { version = "1.27.0", features = ["full"] }
